name: ranking_fairness
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - pip
  - jupyter
  - numpy
  - tqdm
  - conda-forge::matplotlib
  - torchvision
  - cpuonly
  - torchaudio
  - conda-forge::loguru
